---
title: "R & Python"
author: "Juan David Varela R"
date: "5/4/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate

```{r}
library(reticulate)
use_python("/Users/juandavid/anaconda3/bin/python3")
# py_install("Nombre del paquete a instalar")

os <- import("os")
os$listdir(".")
```

```{r}
source_python("add.py")

add(3, 4)
```

```{r}
np <- import("numpy", convert = FALSE)

x <- np$array(c(1:4))
sum <- x$cumsum()

print(sum)

py_to_r(sum)
```

## Ayuda

```{r}
help(py_to_r)
py_help(os$chdir)
```

## Arrays
```{r}
a <- np_array(c(1:10), order = "C")
a
```

```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```

```{python}
import numpy as np
import pandas as pd

r.datos_py.head()
```

## Sparse Matrix

```{r}
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N, N)
  )
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

```{python}
r.sparse_mat_py
```

```{r}
py_to_r(sparse_mat_py)
```

# Pregunta 1

```{r}

v1 = c(1, 2, 3, 4, 4, 3, 2, 1, 0, 1, 0, 2, 3, 0, 4, 0)
A = matrix(v1, nrow = 4, byrow = T)

v2 = c(4, 3, 2, 1, 0, 3, 0, 4, 1, 2, 3, 4, 0, 1, 0, 2)
B = matrix(v2, nrow = 4, byrow= T)

# Operaciones

A %*% B
B %*% A
t(A %*% B)
t(B) %*% A
solve(A %*% B)
solve(A) %*% t(B)
```

$$A \cdot B =\begin{pmatrix} 1 & 2 & 3 & 4\\ 4 & 3 & 2 & 1\\ 0 & 1 & 0 & 2\\ 3 & 0 & 4 & 0\end{pmatrix} \cdot \begin{pmatrix} 4 & 3 & 2 & 1\\ 0 & 3 & 0 & 4\\ 1 & 2 & 3 & 4\\ 0 & 1 & 0 & 2\end{pmatrix} = \begin{pmatrix} 7 & 19 & 11 & 29\\ 18 & 26 & 14 & 26\\ 0 & 5 & 0 & 8\\ 16 & 17 & 18 & 19\end{pmatrix}$$

$$B \cdot A =\begin{pmatrix} 4 & 3 & 2 & 1\\ 0 & 3 & 0 & 4\\ 1 & 2 & 3 & 4\\ 0 & 1 & 0 & 2\end{pmatrix} \cdot \begin{pmatrix} 1 & 2 & 3 & 4\\ 4 & 3 & 2 & 1\\ 0 & 1 & 0 & 2\\ 3 & 0 & 4 & 0\end{pmatrix} = \begin{pmatrix} 19 & 19 & 22 & 23\\ 24 & 9 & 22 & 3\\ 21 & 11 & 23 & 12\\ 10 & 3 & 10 & 1\end{pmatrix}$$

# Pregunta 2

$$dni = (1, 1, 4, 4, 5, 6, 3, 1, 3, 2)$$

```{r}
dni = c(1, 1, 4, 4, 5, 6, 3, 1, 3, 2)
cuadrado = function(v) {
  v^2
}
raiz = function(v) {
  sqrt(v)
}

cuadrado(dni)
round(raiz(dni), 2)
sum(dni)
```

$$dni^2 = (1, 1, 16, 16, 25, 36, 9, 1, 9, 4)$$

$$\sqrt{dni} = (1, 1, 2, 2, 2.4, 2.45, 1.73, 1, 1.73, 1.41)$$

$$sum(dni) = 30$$

# Pregunta 3

$$NombreCompleto = (J, U, A, N, V, A, R, E, L, A)$$

```{r}
nombre = c("J", "U", "A", "N", "V", "A", "R", "E", "L", "A")
nombre[1:4]
nombre[5:length(nombre)]
sort(nombre)
rbind(nombre[1:4], nombre[5:length(nombre)])
```

$$Nombre = (J, U, A, N)$$
$$Apellido = (V, A, R, E, L, A)$$

$$OrdenAlfabético = (A, A, A, E, J, L, N, R, U, V)$$

$$MatrizNombres = \begin{pmatrix} J & U & A & N & J & U \\ V & A & R & E & L & A\end{pmatrix}$$